apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-config
data:
  RANDOM_ROUTE: {{ .Values.randomRoute | toString }}
  TIMEOUT: "{{ .Values.timeout }}"
  BUILD_PACKS: |
    {{- range .Values.buildPacks }}
    - {{ . }}
    {{- end }}
  INSTANCES: "{{ .Values.instances }}"
